# Template originally came from:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Syntax checks
cargo-check:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - maint/update-bizarre --check
    - rustup component add rustfmt
    - mv Cargo.lock.example Cargo.lock
    - cargo check --locked --workspace --verbose --all-features
    - cargo fmt --verbose --check


# Actual tests
cargo-test:
  stage: test
  # Pin to a particular nightly, so our macro expansions don't change.
  image: rustlang/rust@sha256:415b7c22ab4a8a3ec3efc9cc8d7b018964f0c6757fff27bbd110e0ed92566321
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - ./maint/via-cargo-install-in-ci cargo-expand
    - mv Cargo.lock.example Cargo.lock
    - cargo test --locked --workspace --verbose --all-features
  cache:
    paths:
      - cargo-expand
