[package]
name = "derive-adhoc"
version = "0.0.1"
edition = "2018"
license="MIT"
authors=["Ian Jackson <ijackson@chiark.greenend.org.uk>",
         "and the contributors to Rust derive-adhoc"]
description="An ergonomic way to write derive() macros"
homepage = "https://gitlab.torproject.org/Diziet/rust-derive-adhoc"

[workspace]
members = ["macros"]

[dependencies]
derive-adhoc-macros = { path = "macros", version = "0.0.1" }

[dev-dependencies]
trybuild = "1"
