[package]
name = "derive-adhoc"
version = "0.1.0"
edition = "2018"
license="MIT"
authors=["Ian Jackson <ijackson@chiark.greenend.org.uk>",
         "and the contributors to Rust derive-adhoc"]
description="An ergonomic way to write derive() macros"
homepage = "https://gitlab.torproject.org/Diziet/rust-derive-adhoc"
repository = "https://gitlab.torproject.org/Diziet/rust-derive-adhoc"

autotests = false

[workspace]
members = [
	"macros",
	"tests",
	"tests/pub-export/pub-a",
	"tests/pub-export/pub-b",
]

[dependencies]
derive-adhoc-macros = { path = "macros", version = "0.1.0" }
heck = "0.4"
