#!/usr/bin/perl -w
#
# usage:
#   maint/update-bizarre [--check]
#
# Updates the Cargo.toml files in tests/pub-export/bizarre-*
# from the main ones in /Cargo.toml and /macros/Cargo.toml.
#
# We do it like this mostly because a build.rs seems like it would be
# worse.  These files only need to be updated when we update
# dependencies or something.  And, this is not the only thing that
# needs an automatic update to a checked-in file: Cargo.lock does too.

use Carp;
use Getopt::Long;

our $check;

GetOptions(
	   "check" => \$check,
	  )
  or die("$0: bad usage\n");

our $bizvsn = '0.0.666';
our $found_differences = 0;

# This is an anonymous 
sub process_cargo_toml ($$$$) {
    my ($input, $output, $src_path, $before_lib) = @_;
(sub { # anonymous subref has its own `...` operator state

    open I, $input or confess "$input: $!";
    open O, ">$output.new" or confess "$output: $!";

    my $pkg;

    my $had_lib;
    my $in_lib = <<END;
path = "../../../$src_path"
doc = false
doctest = false
END

    while (<I>) {
	s{(\S)[ \t]+}{$1 }g;
	s{\s+$}{\n};
	if (m{^\[package\]}...m{^\[}) {
	    s{^name ?= ?"([^"]+)"$}{name = "bizarre-$1"} and $pkg=$1;
	    s{^version ?=.*}{version = "$bizvsn"};
	    s{^(?:homepage|repository|readme) ?=.*\n}{};
	    $_ = <<END if m{^description ?=.*};
description="Bizarrely incompatible copy of $pkg, for testing"

publish = false
END
	}
	if (m{^\[dependencies\]}...m{^\[}) {
	    $_ = <<END if m{^(\S+) ?= ?\{ ?path ?= ?"([^"]+)".*};
$1 = { package = "bizarre-$1", path = "../bizarre-$2", version = "$bizvsn" }
END
        }
	if (m{^\[lib\]}...m{^\[}) {
	    if (m{^\[lib\]}) {
		$had_lib = 1;
		$_ = $before_lib . $_ . $in_lib;
	    }
	    s{^(?:path|doc|doctest) ?=.*\n}{};
	}
	next if (m{^\[workspace\]}...m{^\[}) && m{^\[workspace\]|^[^\[]};
	print O or confess $!;
    }
    if (!$had_lib) {
	print O "\n".$before_lib."[lib]\n".$in_lib or confess $!;
    }
    
    I->error and confess $!;
    O->error and confess $!;
    close O or confess $!;


    if ($check) {
	my $r = system 'diff', '-u', "$output", "$output.new";
	$r == 0 || $r == 256 || confess 'diff failed';
	if ($r) {
	    $found_differences ||= 1;
	} else {
	    unlink "$output.new" or confess $!;
	}
    } else {
	rename "$output.new", "$output" or confess "$input: $!";
    }

})->()
}

process_cargo_toml('Cargo.toml',
		   'tests/pub-export/bizarre-facade/Cargo.toml',
		   'src/lib.rs', '');

process_cargo_toml('macros/Cargo.toml',
		   'tests/pub-export/bizarre-macros/Cargo.toml',
		   'macros/macros.rs', <<END);
[features]
bizarre = []
default = ["bizarre"]

END

if ($found_differences) {
    die "$0: --check, found differences.  Rerun $0 and commit.";
}
