[package]
name = "derive-adhoc-macros"
version = "0.0.1"
edition = "2018"

[dependencies]
itertools = "0.10"
proc-macro2 = "1"
quote = "1"
strum = { version = "0.24", features = ["derive"] }
syn = "1"
void = "1"

[lib]
path = "macros.rs"
proc-macro = true
